/**
 * DO NOT EDIT
 * This file has been autogenerated by ./generate.mjs
 */

/* eslint-disable */

declare class Headers {
    private headers;
    constructor(init?: Record<string, string> | string[][]);
    private addValue;
    append(name: string, value: string): void;
    delete(name: string): void;
    entries(): IterableIterator<[string, string]>;
    get(name: string): string | undefined;
    has(name: string): boolean;
    keys(): IterableIterator<string>;
    set(name: string, value: string): void;
    values(): IterableIterator<string>;
}

interface RequestInit {
    method?: string;
    headers?: Headers | Record<string, string>;
    body?: string;
}
declare class Request {
    method: string;
    headers: Headers;
    body?: string;
    url: string;
    constructor(input: string, options?: RequestInit);
    text(): Promise<string>;
    json<T>(): Promise<T>;
    formData(): Promise<Record<string, string>>;
}


declare class Headers {
    private headers;
    constructor(init?: Record<string, string> | string[][]);
    private addValue;
    append(name: string, value: string): void;
    delete(name: string): void;
    entries(): IterableIterator<[string, string]>;
    get(name: string): string | undefined;
    has(name: string): boolean;
    keys(): IterableIterator<string>;
    set(name: string, value: string): void;
    values(): IterableIterator<string>;
}

interface ResponseInit {
    status?: number;
    statusText?: string;
    headers?: Headers | Record<string, string>;
    url?: string;
}
declare class Response {
    body: string;
    headers: Headers;
    ok: boolean;
    status: number;
    statusText: string;
    url: string;
    constructor(body: string, options?: ResponseInit);
    text(): Promise<string>;
    json<T>(): Promise<T>;
    formData(): Promise<Record<string, string>>;
}


declare class URLSearchParams {
    private params;
    constructor(init?: string | Record<string, string> | string[][]);
    private addValue;
    append(name: string, value: string): void;
    delete(name: string): void;
    entries(): IterableIterator<[string, string]>;
    forEach(callback: (value: string, key: string, parent: URLSearchParams) => void, thisArg?: any): void;
    get(name: string): string | undefined;
    getAll(name: string): string[] | undefined;
    has(name: string): boolean;
    keys(): IterableIterator<string>;
    set(name: string, value: string): void;
    sort(): void;
    toString(): string;
    values(): IterableIterator<string>;
}
declare class URL {
    hash: string;
    host: string;
    hostname: string;
    href: string;
    origin: string;
    password: string;
    pathname: string;
    port: string;
    protocol: string;
    search: string;
    searchParams: URLSearchParams | null;
    username: string;
    constructor(url: string, base?: string);
    toString(): string;
}


declare function atob(encodedData: string): string;
declare function btoa(stringToEncode: string): string;


declare class TextEncoder {
    encoding: string;
    encode(string: string): Uint8Array;
}
declare class TextDecoder {
    encoding: string;
    decode(buffer: Iterable<number>): string;
}


interface RequestInit {
    method?: string;
    headers?: Headers | Record<string, string>;
    body?: string;
}

interface ResponseInit {
    status?: number;
    statusText?: string;
    headers?: Headers | Record<string, string>;
    url?: string;
}
declare class Response {
    body: string;
    headers: Headers;
    ok: boolean;
    status: number;
    statusText: string;
    url: string;
    constructor(body: string, options?: ResponseInit);
    text(): Promise<string>;
    json<T>(): Promise<T>;
    formData(): Promise<Record<string, string>>;
}

declare class Headers {
    private headers;
    constructor(init?: Record<string, string> | string[][]);
    private addValue;
    append(name: string, value: string): void;
    delete(name: string): void;
    entries(): IterableIterator<[string, string]>;
    get(name: string): string | undefined;
    has(name: string): boolean;
    keys(): IterableIterator<string>;
    set(name: string, value: string): void;
    values(): IterableIterator<string>;
}
declare function fetch(resource: string, init: RequestInit): Promise<Response>;


declare const fs: {
    readFile: (path: string) => Promise<string>;
};


declare class Headers {
    private headers;
    constructor(init?: Record<string, string> | string[][]);
    private addValue;
    append(name: string, value: string): void;
    delete(name: string): void;
    entries(): IterableIterator<[string, string]>;
    get(name: string): string | undefined;
    has(name: string): boolean;
    keys(): IterableIterator<string>;
    set(name: string, value: string): void;
    values(): IterableIterator<string>;
}

declare const parseMultipart: (headers: Headers, body?: string) => Record<string, string>;


