[workspace]
members = [
  "crates/runtime",
  "crates/serverless",
  "crates/cli",
  "crates/wpt-runner",
]

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"

[profile.dev.package.num-bigint-dig]
opt-level = 3