[package]
name = "lagon-serverless-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
lagon-runtime-utils = { path = "../runtime_utils" }
anyhow = "1.0.71"
async-trait = "0.1.71"
rust-s3 = "0.33"
