[package]
name = "lagon-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3.21"
v8 = "0.45.0"
lazy_static = "1.4.0"

[dev-dependencies]
lazy_static = "1.4.0"
