[package]
name = "lagon-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
v8 = "0.45.0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["blocking"] }
