[package]
name = "lagon-runtime-isolate"
version = "0.1.0"
edition = "2021"

[dependencies]
v8 = "0.66.0"
tokio = { version = "1", features = ["rt-multi-thread"] }
tokio-util = { version = "0.7.7", features = ["rt"] }
futures = "0.3.27"
hyper = { version = "0.14", features = ["client"] }
hyper-tls = { version = "0.5.0", features = ["vendored"] }
flume = "0.10.14"
anyhow = "1.0.70"
log = { version = "0.4.17", features = ["std", "kv_unstable"] }
lazy_static = "1.4.0"
async-recursion = "1.0.4"
linked-hash-map = "0.5.6"
lagon-runtime-v8-utils = { path = "../runtime_v8_utils" }
lagon-runtime-http = { path = "../runtime_http" }
lagon-runtime-crypto = { path = "../runtime_crypto" }

[features]
default = []
ignore-snapshot = []
