name: Container

on:
  push:
    branches:
      - main
    tags:
      - '@lagon/serverless@*'
  pull_request:

env:
  DOCKER_HUB_USER: lagonapp

jobs:
  create-container-image:
    name: Create "${{matrix.image}}" container image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # image: [serverless, dashboard]
        image: [serverless]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKER_HUB_USER }}/${{matrix.image}}
            ghcr.io/${{ github.repository_owner }}/${{matrix.image}}
          tags: |
            type=ref,event=tag,prefix=@lagon/${{matrix.image}}@
            type=ref,event=pr
            type=raw,value=next,enable={{is_default_branch}}

      - name: Login to ghcr.io registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        if: "!startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, format('refs/tags/{0}', matrix.image))"
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: docker/Dockerfile.${{matrix.image}}
          platforms: linux/amd64,linux/arm64
