name: web-platform-tests
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  wpt:
    name: web-platform-tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: moonrepo/setup-rust@v0
      - uses: pnpm/action-setup@v2.4.0
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build runtime
        run: pnpm turbo build --filter=@lagon/js-runtime
      - name: Run wpt-runner
        run: cd crates/wpt-runner && pnpm start
      - name: Check if results have changed
        run: git diff --exit-code
