[package]
name = "lagon-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
lagon-runtime = { path = "../rust-runtime" }
clap = { version = "3.2", features = ["derive"] }
dialoguer = "0.10.2"
dirs = "4.0.0"
webbrowser = "0.8.0"
reqwest = { version = "0.11", features = ["json", "multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
